/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TypeaheadDatasource, TypeheadDataItem, } from "./contracts/typeahead-datasource";
import { TypeaheadItemRendererProps, } from "./contracts/typeahead-item-renderer-props";
export namespace Components {
    interface DhiCountryTypeahead {
    }
    interface DhiTypeahead {
        "datasource"?: TypeaheadDatasource;
        "itemRender"?: (props: TypeaheadItemRendererProps) => any;
    }
    interface LocationEntryForm {
    }
}
declare global {
    interface HTMLDhiCountryTypeaheadElement extends Components.DhiCountryTypeahead, HTMLStencilElement {
    }
    var HTMLDhiCountryTypeaheadElement: {
        prototype: HTMLDhiCountryTypeaheadElement;
        new (): HTMLDhiCountryTypeaheadElement;
    };
    interface HTMLDhiTypeaheadElement extends Components.DhiTypeahead, HTMLStencilElement {
    }
    var HTMLDhiTypeaheadElement: {
        prototype: HTMLDhiTypeaheadElement;
        new (): HTMLDhiTypeaheadElement;
    };
    interface HTMLLocationEntryFormElement extends Components.LocationEntryForm, HTMLStencilElement {
    }
    var HTMLLocationEntryFormElement: {
        prototype: HTMLLocationEntryFormElement;
        new (): HTMLLocationEntryFormElement;
    };
    interface HTMLElementTagNameMap {
        "dhi-country-typeahead": HTMLDhiCountryTypeaheadElement;
        "dhi-typeahead": HTMLDhiTypeaheadElement;
        "location-entry-form": HTMLLocationEntryFormElement;
    }
}
declare namespace LocalJSX {
    interface DhiCountryTypeahead {
    }
    interface DhiTypeahead {
        "datasource"?: TypeaheadDatasource;
        "itemRender"?: (props: TypeaheadItemRendererProps) => any;
        "onItemChange"?: (event: CustomEvent<TypeheadDataItem>) => void;
    }
    interface LocationEntryForm {
    }
    interface IntrinsicElements {
        "dhi-country-typeahead": DhiCountryTypeahead;
        "dhi-typeahead": DhiTypeahead;
        "location-entry-form": LocationEntryForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dhi-country-typeahead": LocalJSX.DhiCountryTypeahead & JSXBase.HTMLAttributes<HTMLDhiCountryTypeaheadElement>;
            "dhi-typeahead": LocalJSX.DhiTypeahead & JSXBase.HTMLAttributes<HTMLDhiTypeaheadElement>;
            "location-entry-form": LocalJSX.LocationEntryForm & JSXBase.HTMLAttributes<HTMLLocationEntryFormElement>;
        }
    }
}
